name: Tests
on: [push]

jobs:
  build:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: UTC

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dssp
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libboost-all-dev zlib1g-dev libbz2-dev
        git clone --branch v4.5.8 --depth 1 https://github.com/PDB-REDO/dssp.git
        cmake -S dssp -B dssp/build
        cmake --build dssp/build --target mkdssp
        cp dssp/build/mkdssp .

    - name: Install stride
      run: |
        git clone https://github.com/MDAnalysis/stride.git stride-src
        cd stride-src
        git checkout 867a5eb0f2479cb16615512a53ee472c54649505
        make -C src
        cp src/stride "$GITHUB_WORKSPACE/stride"
        chmod +x "$GITHUB_WORKSPACE/stride"

    - name: Install msms
      run: | 
        conda install -c bioconda msms
        echo "$HOME/miniconda3/bin/msms" >> $GITHUB_PATH

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install ".[dev]"

    - name: Test with pytest
      run: |
        python -m pytest --exitfirst --verbose --failed-first \
        --cov=. --cov-report html
      
