name: Tests
on: [push]

jobs:
  build:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: UTC

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dssp
      run: |
        sudo apt-get install libboost-all-dev
        git clone https://github.com/PDB-REDO/libcifpp.git
        cd libcifpp/
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release
        cmake --install .
        cd ../..
        
    - name: Install Python dependencies
      run: |
        pip3 install -r requirements.txt

    - name: Test with pytest
      run: |
        pytest --exitfirst --verbose --failed-first \
        --cov=. --cov-report html
