name: Tests
on: [push]

jobs:
  build:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: UTC

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dssp
      run: |
        sudo apt-get install libboost-all-dev
        git clone https://github.com/PDB-REDO/libcifpp.git
        cd libcifpp/
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release
        cmake --install .
        cd ../..
        git clone https://github.com/PDB-REDO/dssp.git
        cd dssp
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release
        cmake --install .

    - name: Install stride
      run: |
        wget http://webclu.bio.wzw.tum.de/stride/stride.tar.gz
        mkdir stride-src
        mv stride.tar.gz stride-src/
        cd stride-src
        tar zxvf stride.tar.gz
        make
        cp stride ..
        cd ..

    - name: Install Python dependencies
      run: |
        pip3 install -r requirements.txt

    - name: Test with pytest
      run: |
        pytest --exitfirst --verbose --failed-first \
        --cov=. --cov-report html
