name: Tests
on: [push]

jobs:
  build:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: UTC

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dssp
      run: |
        sudo apt-get install libboost-all-dev
        wget https://github.com/cmbi/dssp/archive/refs/tags/2.3.0.zip
        mv 2.3.0.zip dssp-2.3.0.zip
        unzip dssp-2.3.0.zip
        cd dssp-2.3.0
        ./autogen.sh
        ./configure
        make mkdssp
        cp mkdssp ..

    - name: Install stride
      run: |
        wget http://webclu.bio.wzw.tum.de/stride/stride.tar.gz
        mkdir stride-src
        mv stride.tar.gz stride-src/
        cd stride-src
        tar zxvf stride.tar.gz
        make
        cp stride ..
        cd ..

    - name: Install Python dependencies
      run: |
        pip3 install -r requirements.txt

    - name: Test with pytest
      run: |
        pytest --exitfirst --verbose \
        --cov . 

    - name: Upload coverage reports to Codecov
      run: |
        # Replace `linux` below with the appropriate OS
        # Options are `alpine`, `linux`, `macos`, `windows`
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov 